app:
  name: "Go Microservice Boilerplate"
  version: "1.0.0"
  environment: "development"
  debug: true

# Logging configuration
logging:
  level: "info"          # debug, info, warn, error, fatal, panic
  format: "json"         # json, text
  caller: false          # Enable caller information
  file:
    enabled: false
    path: "logs/app.log"
    max_size: 100        # megabytes
    max_backups: 3
    max_age: 28          # days
    compress: true

# Server configuration
server:
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  graceful_timeout: 15s

# Database configuration
database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "microservices_db"
    timeout: 30
    max_pool_size: 10
    min_pool_size: 5
    max_idle_time: 300    # seconds
    retry:
      max_attempts: 3
      delay: 1s

  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5
    dial_timeout: 5s
    read_timeout: 3s
    write_timeout: 3s
    pool_timeout: 4s
    idle_timeout: 300s    # 5 minutes
    max_retries: 3

# Service configuration
services:
  gateway:
    port: "8080"
    host: "0.0.0.0"
    cors:
      enabled: true
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allowed_headers: ["Origin", "Content-Type", "Accept", "Authorization", "X-Request-ID"]
      exposed_headers: ["X-Request-ID"]
      max_age: 3600
    rate_limit:
      enabled: true
      requests_per_minute: 100
      burst: 50

  user:
    port: "50051"
    host: "0.0.0.0"
    timeout: 30s
    max_connections: 1000

  product:
    port: "50052"
    host: "0.0.0.0"
    timeout: 30s
    max_connections: 1000

# Security configuration
security:
  jwt:
    secret: "dev-secret"
    expiration: 3600      # seconds (1 hour)
    refresh_expiration: 604800  # seconds (7 days)
    issuer: "go-microservice-boilerplate"
    algorithm: "HS256"

  password:
    min_length: 6
    require_uppercase: false
    require_lowercase: false
    require_numbers: false
    require_symbols: false
    bcrypt_cost: 12

# Cache configuration
cache:
  default_expiration: 3600    # seconds (1 hour)
  cleanup_interval: 600       # seconds (10 minutes)

  expiration:
    short: 300                # 5 minutes
    medium: 1800              # 30 minutes
    long: 3600                # 1 hour
    very_long: 86400          # 24 hours

swagger:
  enabled: true
  auth:
    enabled: true
    username: "admin"
    password: "swagger123"
  title: "Go Microservice API"
  version: "1.0.0"
  description: "Microservice API for user and product management"